### ISSUE TITLE
How to actually get the cookie info

### ISSUE THREAD

**Issue by PetrG7** [avilash/TikTokAPI-Python#22]
Hi,

i am unable to get the cookie info. I don't know if I am dumb or what but I just cant seem to find it :/ . This is my applications tab screenshot. Please where are the cookies. Thanks in advance.

![image](https://user-images.githubusercontent.com/30552834/105472102-cdf4f080-5c9b-11eb-8bb1-7ea50bf520ba.png)

**Comment by PetrG7** [comment]
Nvm i actually resolved it. I am just blind xd.

**Comment by ROBGUI09** [comment]
> Nvm i actually resolved it. I am just blind xd.

How??
